packages:
  - "."

nodeLinker: hoisted

allowBuilds:
  "@parcel/watcher": false
  electron: true
  electron-winstaller: true
  esbuild: true
  phantomjs-prebuilt: true
  vue-demi: true

overrides:
  "form-data@2": 2.5.6
  "form-data@4": 4.0.6
  plist: 3.1.1
